### PR TITLE
Change Fnal collector. To be merged on Monday

### PR DESCRIPTION
**Pull request by juztas**

### CODE REVIEW

**Comment by bbockelm** [comment]
@juztas - it's Monday, should we merge?

**Comment by juztas** [comment]
yes. @h4d4 can you deploy new code? It is mainly config change which lives under /etc/prodview.conf

**Comment by h4d4** [comment]
@juztas 
Sure, let me do it when it needs to be done?

Best Regards, Lina.

**Comment by h4d4** [comment]
@juztas Hi Justas,

just to confirm that I've deployed this PR, today around 10:35 GVA time 

Best Regards, Lina.

**Pull request merged**
